print("""☺︎!!!! Mad Libs Generator!!!!☺︎
-----------------------------
""")
print("noun: person, place, or thing")
print("adjective: describes a noun")
print("verb: action word")
print("       ")
loop = 1
while (loop < 5):
    adjective = input("An adjective: ")
    adjective2 = input("An adjective: ")
    bird = input("A type of bird: ")
    room = input("A room in a house: ")
    verb = input("A verb (past tense): ")
    verb2 = input("A verb: ")
    name = input ("Relative's name: ")
    noun = input("A noun: ")
    liquid = input ("A liquid: ")
    verb3 = input ("A verb ending in -ing: ")
    part = input ("A part of the body (plural): ")
    noun2 = input ("A plural noun: ")
    verb4 = input("A verb ending in -ing: ")
    noun3 = input ("A noun: ")
    print ("------------------------------------------")
    print ("It was a",adjective,"November day. I woke up to the",adjective2)
    print ("smell of",bird,"roasting in the", room,"downstairs. I",verb)
    print ("down the stairs to see if I could help",verb2,"the dinner. My mom told me")
    print ("that",name,"needs a fresh",noun,". So I carried a tray with")
    print ("glasses full of",liquid,"into the",verb3,"room.")
    print ("When I got there, I couldn't believe my",part,"! There were")
    print (noun2, verb4,"on the",noun3,".")
    print ()
    print ("------------------------------------------")
    loop = loop + 1
